apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: test
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
